### ISSUE TITLE
Can't download pretrained model

### ISSUE THREAD

**Issue by wlxzt** [Zeqiang-Lai/Prosody_Prediction#1]
Hello,

I'd like to run your prediction demo but the download link in `pretrained/download_biaobei_pretrained.sh` is not valid anymore, could you please make some update? 

Thanks a lot.

**Comment by Zeqiang-Lai** [comment]
Well, here it is, 链接: https://pan.baidu.com/s/1YWH65bM-NGZYOAoK8C3rBQ  密码: 6r1w
unzip and replace the pretrained folder in the repo with the "pretrained" folder in this zip file

**Comment by tuocheng0824** [comment]
Hello,
 
  I'd like to run your prediction demo but the download link in `pretrained/download_biaobei_pretrained.sh` is not valid anymore, could you please make some update?

 Thanks a lot.
