### ISSUE TITLE
embedding model url is not available.

### ISSUE THREAD

**Issue by deyituo** [Zeqiang-Lai/Prosody_Prediction#2]
Hi, 

I search for the embedding model and find the url below. Do you use the v0.1.0 model or v0.2.0?

https://ai.tencent.com/ailab/nlp/en/download.html

**Comment by Zeqiang-Lai** [comment]
The embedding I used was released earlier than 2019, but it seems that the tencent updates the embedding at 2021. Nevertheless, I guess you should use v0.2.0 as it is the Latest Version for Chinese.
